from snakemake.utils import min_version

min_version("9.12.0")


configfile: "config/config.yaml"


include: "rules/helpers.smk"
include: "rules/prepare_data.smk"
include: "rules/perform_colocalization.smk"
