import pandas as pd
import os


configfile: "workflow/config.yaml"


# First rule generates all pairs to test
rule find_pairs:
    input:
        input_signals=config["DATA_DIR"] + "/input_signals.csv",
    output:
        output_pairs=config["OUTPUTS_DIR"] + "/pairs_to_test.csv",
    params:
        distance=config["DISTANCE_LIMIT"],
    script:
        "scripts/generate_analyses.R"


# Read the pairs file to get list of pairs to process
if os.path.exists(config["OUTPUTS_DIR"] + "/pairs_to_test.csv"):
    PAIRS = pd.read_csv(config["OUTPUTS_DIR"] + "/pairs_to_test.csv")[
        "pair_index"
    ].tolist()
else:
    PAIRS = []


# Aggregation rule that requires all final results
rule all:
    input:
        # First ensure pairs file exists
        config["OUTPUTS_DIR"] + "/pairs_to_test.csv",
        # Then require all coloc results
        expand(config["OUTPUTS_DIR"] + "/coloc_results/{pair_id}.txt", pair_id=PAIRS),


# Extract regions for a single pair
rule extract_regions:
    input:
        pairs=find_pairs.output.output_pairs,
        sumstats_dir=config["SUMSTATS_DIR"],
    output:
        output_joined_sumstats=config["OUTPUTS_DIR"]
        + "/extracted_regions/{pair_id}_sumstats.txt",
    params:
        pair_id="{pair_id}",
    script:
        "scripts/extract_regions.R"


# Run coloc on a pair of extracted regions
rule run_coloc:
    input:
        input_signals=config["DATA_DIR"] + "/input_signals.csv",
        input_pairs=find_pairs.output.output_pairs,
        input_joined_sumstats=config["OUTPUTS_DIR"]
        + "/extracted_regions/{pair_id}_sumstats.txt",
    params:
        pair_id="{pair_id}",
    output:
        output_results=config["OUTPUTS_DIR"] + "/coloc_results/{pair_id}.txt",
    script:
        "scripts/run_coloc.R"
